name: video_player_example
description: Demonstrates how to use the video_player plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter


dependency_overrides: 
  video_player: 
    git: 
      url: https://github.com/bdezso/plugins
      path: packages/video_player/video_player
      ref: observe-boundary-timing
  video_player_platform_interface: 
    git: 
      url: https://github.com/bdezso/plugins
      path: packages/video_player/video_player_platform_interface
      ref: observe-boundary-timing


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.6
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
