name: video_player_avfoundation
description: iOS implementation of the video_player plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/video_player/video_player_avfoundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.3.5

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FLTVideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5

dependency_overrides:
  video_player: 
    git: 
      url: https://github.com/bdezso/plugins
      path: packages/video_player/video_player
      ref: observe-boundary-timing
  video_player_android: 
    git: 
      url: https://github.com/bdezso/plugins
      path: packages/video_player/video_player_android
      ref: observe-boundary-timing
  video_player_platform_interface: 
    git: 
      url: https://github.com/bdezso/plugins
      path: packages/video_player/video_player_platform_interface
      ref: observe-boundary-timing
  video_player_web: 
    git: 
      url: https://github.com/bdezso/plugins
      path: packages/video_player/video_player_web
      ref: observe-boundary-timing


dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
